//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sim.Sec.Governo.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sim.Sec.Governo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Sim.Sec.Governo;component/Legislacao/View/pAdd.xaml.
        /// </summary>
        public static string Sec_Governo_Legislacao_Add {
            get {
                return ResourceManager.GetString("Sec_Governo_Legislacao_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Sim.Sec.Governo;component/Legislacao/View/pConfig.xaml.
        /// </summary>
        public static string Sec_Governo_Legislacao_Config {
            get {
                return ResourceManager.GetString("Sec_Governo_Legislacao_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Sim.Sec.Governo;component/Legislacao/View/Pages/pAcao.xaml.
        /// </summary>
        public static string Sec_Governo_Legislacao_Config_Acao {
            get {
                return ResourceManager.GetString("Sec_Governo_Legislacao_Config_Acao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Sim.Sec.Governo;component/Legislacao/View/Pages/pAutor.xaml.
        /// </summary>
        public static string Sec_Governo_Legislacao_Config_Autor {
            get {
                return ResourceManager.GetString("Sec_Governo_Legislacao_Config_Autor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Sim.Sec.Governo;component/Legislacao/View/Pages/pClassDec.xaml.
        /// </summary>
        public static string Sec_Governo_Legislacao_Config_ClassDec {
            get {
                return ResourceManager.GetString("Sec_Governo_Legislacao_Config_ClassDec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Sim.Sec.Governo;component/Legislacao/View/Pages/pClassLoLc.xaml.
        /// </summary>
        public static string Sec_Governo_Legislacao_Config_ClassLLc {
            get {
                return ResourceManager.GetString("Sec_Governo_Legislacao_Config_ClassLLc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Sim.Sec.Governo;component/Legislacao/View/Pages/pLinkPdf.xaml.
        /// </summary>
        public static string Sec_Governo_Legislacao_Config_LinkPDF {
            get {
                return ResourceManager.GetString("Sec_Governo_Legislacao_Config_LinkPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Sim.Sec.Governo;component/Legislacao/View/Pages/pOrigem.xaml.
        /// </summary>
        public static string Sec_Governo_Legislacao_Config_Origem {
            get {
                return ResourceManager.GetString("Sec_Governo_Legislacao_Config_Origem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Sim.Sec.Governo;component/Legislacao/View/Pages/pSituacao.xaml.
        /// </summary>
        public static string Sec_Governo_Legislacao_Config_Situacao {
            get {
                return ResourceManager.GetString("Sec_Governo_Legislacao_Config_Situacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Sim.Sec.Governo;component/Legislacao/View/Pages/pTipos.xaml.
        /// </summary>
        public static string Sec_Governo_Legislacao_Config_Tipo {
            get {
                return ResourceManager.GetString("Sec_Governo_Legislacao_Config_Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Sim.Sec.Governo;component/Legislacao/View/pEdite.xaml.
        /// </summary>
        public static string Sec_Governo_Legislacao_Edit {
            get {
                return ResourceManager.GetString("Sec_Governo_Legislacao_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Sim.Sec.Governo;component/Legislacao/View/pMainPage.xaml.
        /// </summary>
        public static string Sec_Governo_Legislacao_Main {
            get {
                return ResourceManager.GetString("Sec_Governo_Legislacao_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Sim.Sec.Governo;component/Legislacao/View/pReports.xaml.
        /// </summary>
        public static string Sec_Governo_Legislacao_Report {
            get {
                return ResourceManager.GetString("Sec_Governo_Legislacao_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Sim.Sec.Governo;component/Legislacao/View/pConsulta.xaml.
        /// </summary>
        public static string Sec_Governo_Legislacao_Search {
            get {
                return ResourceManager.GetString("Sec_Governo_Legislacao_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Sim.Sec.Governo;component/Legislacao/View/pConsultaC.xaml.
        /// </summary>
        public static string Sec_Governo_Legislacao_Search_Advanced {
            get {
                return ResourceManager.GetString("Sec_Governo_Legislacao_Search_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Sim.Sec.Governo;component/Menu/View/pMain.xaml.
        /// </summary>
        public static string Sec_Governo_Menu {
            get {
                return ResourceManager.GetString("Sec_Governo_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Sim.Sec.Governo;component/NomesPublicos/View/pAdd.xaml.
        /// </summary>
        public static string Sec_Governo_NomesPublicos_Add {
            get {
                return ResourceManager.GetString("Sec_Governo_NomesPublicos_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Sim.Sec.Governo;component/NomesPublicos/View/pMain.xaml.
        /// </summary>
        public static string Sec_Governo_NomesPublicos_Main {
            get {
                return ResourceManager.GetString("Sec_Governo_NomesPublicos_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Sim.Sec.Governo;component/NomesPublicos/View/pReport.xaml.
        /// </summary>
        public static string Sec_Governo_NomesPublicos_Report {
            get {
                return ResourceManager.GetString("Sec_Governo_NomesPublicos_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Sim.Sec.Governo;component/NomesPublicos/View/pSearch.xaml.
        /// </summary>
        public static string Sec_Governo_NomesPublicos_Search {
            get {
                return ResourceManager.GetString("Sec_Governo_NomesPublicos_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Sim.Sec.Governo;component/Portarias/View/pAdd.xaml.
        /// </summary>
        public static string Sec_Governo_Portarias_Add {
            get {
                return ResourceManager.GetString("Sec_Governo_Portarias_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Sim.Sec.Governo;component/Portarias/View/pConfig.xaml.
        /// </summary>
        public static string Sec_Governo_Portarias_Config {
            get {
                return ResourceManager.GetString("Sec_Governo_Portarias_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Sim.Sec.Governo;component/Portarias/View/Pages/pClassf.xaml.
        /// </summary>
        public static string Sec_Governo_Portarias_Config_Classificacao {
            get {
                return ResourceManager.GetString("Sec_Governo_Portarias_Config_Classificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Sim.Sec.Governo;component/Portarias/View/Pages/pLinkPdf.xaml.
        /// </summary>
        public static string Sec_Governo_Portarias_Config_PDF {
            get {
                return ResourceManager.GetString("Sec_Governo_Portarias_Config_PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Sim.Sec.Governo;component/Portarias/View/pEdite.xaml.
        /// </summary>
        public static string Sec_Governo_Portarias_Edit {
            get {
                return ResourceManager.GetString("Sec_Governo_Portarias_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Sim.Sec.Governo;component/Portarias/View/pMainPage.xaml.
        /// </summary>
        public static string Sec_Governo_Portarias_Main {
            get {
                return ResourceManager.GetString("Sec_Governo_Portarias_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Sim.Sec.Governo;component/Portarias/View/pReports.xaml.
        /// </summary>
        public static string Sec_Governo_Portarias_Report {
            get {
                return ResourceManager.GetString("Sec_Governo_Portarias_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Sim.Sec.Governo;component/Portarias/View/pSearch.xaml.
        /// </summary>
        public static string Sec_Governo_Portarias_Search {
            get {
                return ResourceManager.GetString("Sec_Governo_Portarias_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a /Sim.Sec.Governo;component/Portarias/View/pSearchAdv.xaml.
        /// </summary>
        public static string Sec_Governo_Portarias_Search_Advanced {
            get {
                return ResourceManager.GetString("Sec_Governo_Portarias_Search_Advanced", resourceCulture);
            }
        }
    }
}
